<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SANGEETHA-PC" ignored="6" name="Default test" tests="2" failures="0" timestamp="04 Aug 2020 17:53:33 GMT" time="22.387" errors="0">
  <testcase name="@AfterMethod tearDown" time="0.005" classname="Test.FunctionalTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Test.FunctionalTest.tearDown(FunctionalTest.java:115)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@BeforeMethod setUp" time="0.0" classname="Test.FunctionalTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="Test.FunctionalTest">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="executePollsTestCases" time="0.011" classname="Test.AudienceTest"/>
  <testcase name="validateTC_AI_066" time="0.0" classname="Test.AudienceTest">
    <skipped/>
  </testcase> <!-- validateTC_AI_066 -->
  <testcase name="validateTC_AI_087" time="0.0" classname="Test.AudienceTest">
    <ignored/>
  </testcase> <!-- validateTC_AI_087 -->
  <testcase name="validateTC_AP_029" time="0.0" classname="Test.AudienceTest">
    <ignored/>
  </testcase> <!-- validateTC_AP_029 -->
  <testcase name="validateTC_AP_074" time="0.0" classname="Test.AudienceTest">
    <ignored/>
  </testcase> <!-- validateTC_AP_074 -->
  <testcase name="validateTC_AI_086" time="0.0" classname="Test.AudienceTest">
    <ignored/>
  </testcase> <!-- validateTC_AI_086 -->
  <testcase name="validateTC_AP_064" time="0.0" classname="Test.AudienceTest">
    <ignored/>
  </testcase> <!-- validateTC_AP_064 -->
  <testcase name="validateTC_AI_073" time="0.0" classname="Test.AudienceTest">
    <ignored/>
  </testcase> <!-- validateTC_AI_073 -->
</testsuite> <!-- Default test -->
