<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SANGEETHA-PC" ignored="9" name="Test" tests="1" failures="1" timestamp="12 Aug 2020 17:33:48 GMT" time="93.744" errors="0">
  <testcase name="validateTC_N_033" time="73.873" classname="Test.NotificationTest">
    <failure type="java.lang.AssertionError" message="expected [] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [] but found [5]
at Test.NotificationTest.validateTC_N_033(NotificationTest.java:634)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- validateTC_N_033 -->
  <testcase name="validateTC_N_013" time="0.0" classname="Test.NotificationTest">
    <ignored/>
  </testcase> <!-- validateTC_N_013 -->
  <testcase name="validateTC_N_020" time="0.0" classname="Test.NotificationTest">
    <ignored/>
  </testcase> <!-- validateTC_N_020 -->
  <testcase name="validateTC_N_007" time="0.0" classname="Test.NotificationTest">
    <ignored/>
  </testcase> <!-- validateTC_N_007 -->
  <testcase name="validateTC_N_029" time="0.0" classname="Test.NotificationTest">
    <ignored/>
  </testcase> <!-- validateTC_N_029 -->
  <testcase name="validateTC_N_028" time="0.0" classname="Test.NotificationTest">
    <ignored/>
  </testcase> <!-- validateTC_N_028 -->
  <testcase name="validateTC_N_017" time="0.0" classname="Test.NotificationTest">
    <ignored/>
  </testcase> <!-- validateTC_N_017 -->
  <testcase name="validateTC_N_003" time="0.0" classname="Test.NotificationTest">
    <ignored/>
  </testcase> <!-- validateTC_N_003 -->
  <testcase name="validateTC_N_004" time="0.0" classname="Test.NotificationTest">
    <ignored/>
  </testcase> <!-- validateTC_N_004 -->
  <testcase name="validateTC_N_015" time="0.0" classname="Test.NotificationTest">
    <ignored/>
  </testcase> <!-- validateTC_N_015 -->
</testsuite> <!-- Test -->
